### ISSUE TITLE
Can't build on Ubuntu 20.10

### ISSUE THREAD

**Issue by mrpavlikov** [brektrou/rtl8821CU#89]
After upgrading to Ubuntu 20.10 driver stopped working. It was fine after upgrade from 19.10 to 20.04.

I can't build both master and 5.8.1. I get following error:

```
/home/mrpavlikov/Downloads/rtl8821CU-5.8.1/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:23,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /home/mrpavlikov/Downloads/rtl8821CU-5.8.1/include/osdep_service_linux.h:49,
                 from /home/mrpavlikov/Downloads/rtl8821CU-5.8.1/include/osdep_service.h:53,
                 from /home/mrpavlikov/Downloads/rtl8821CU-5.8.1/include/drv_types.h:27,
                 from /home/mrpavlikov/Downloads/rtl8821CU-5.8.1/core/rtw_cmd.c:17:
./include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:290: /home/mrpavlikov/Downloads/rtl8821CU-5.8.1/core/rtw_cmd.o] Error 1
make[1]: *** [Makefile:1780: /home/mrpavlikov/Downloads/rtl8821CU-5.8.1] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.8.0-26-generic'
make: *** [Makefile:2327: modules] Error 2
```

SHA256 error pops up when building master as well. Please, advise.

**Comment by mrpavlikov** [comment]
Oh, I see there's patch for this issue in master, but I was not able to build it because I haven't removed previous version of driver. So if anyone faces this issue after upgrade, first run

```
sudo ./dkms-uninstall.sh
```
